inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

AllCops:
  Include:
    - '**/config.ru'
